# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cognito_demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for cognito_demo
  pod 'GoogleSignIn'

  target 'cognito_demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'cognito_demo-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for cognito_demo-tvOS

  target 'cognito_demo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
